### ISSUE TITLE
Sample HDR image looks too bright in Thorium v117

### ISSUE THREAD

**Issue by o-l-a-v** [Alex313031/thorium-libjxl#18]
Here's an image that looks too bright in Thorium v117.0.5938.157 (Official Build) (64-bit):

* https://github.com/gwy15/hdr/blob/main/IMG01623-HDR.jxl

Found here:
* [https://github.com/d2phap/ImageGlass/is ... 1819045271](https://github.com/d2phap/ImageGlass/issues/1677#issuecomment-1819045271)

Here's a screenshot:

![231120 - Cat HDR in GIMP Paint NET XnView MP IrfanView Thorium](https://github.com/Alex313031/thorium-libjxl/assets/6450056/e725dcb5-9e82-4a87-be06-6bb08cca7f51)

* Left: GIMP
* Middle top: IrfanView with https://www.irfanview.net/plugins/jpeg_xl_64.zip
* Middle bottom: Paint.NET v5.0.11 with pdn-jpegxl v1.0.5
* Right top: XnView MP v1.6.1 with ICC enabled
* Right bottom: Thorium v117

**Comment by Alex313031** [comment]
Might just need to update the libjxl library, see > https://github.com/Alex313031/thorium-libjxl/issues/19

**Comment by Alex313031** [comment]
@o-l-a-v I updated it to 0.9.0 in the M120 version. Can you test?

**Comment by o-l-a-v** [comment]
> @o-l-a-v I updated it to 0.9.0 in the M120 version. Can you test?

Thanks, will test tomorrow if I remember it. :)

**Comment by o-l-a-v** [comment]
@Alex313031 

Thorium still struggles with this test image. Thorium v120.0.6099.235 AVX2 to the right, GIMP to the left.

<img width="1279" alt="image" src="https://github.com/Alex313031/thorium-libjxl/assets/6450056/0b235d39-feb6-4812-9169-1906264c6da8">

**Comment by Alex313031** [comment]
@o-l-a-v Nothing more I can do, as I cannot update the libjxl library past 0.9.0. They removed some stuff that it critical for integrating into blink.

**Comment by Traneptora** [comment]
What was removed that was critical for integrating into blink?

**Comment by gz83** [comment]
> What was removed that was critical for integrating into blink?


https://github.com/libjxl/libjxl/commit/b08a704978d5aeaf6fd1e2aee3ae5907a89e1f96

The deleted things are here. We modified the code based on the patches provided by Google engineers, and the version numbers are consistent with those used by Google engineers.

@Traneptora

**Comment by Traneptora** [comment]
How are any of those things critical? Most of them are encoder settings, except for `JxlDecoderGetDefaultPixelForamt` which is noncritical (you either request an image in the pixel format you need, you look at the bit depth tag in the header if you want to use the image's tagged format).

**Comment by Alex313031** [comment]
@Traneptora @o-l-a-v @gz83 We fixed it, as they fixed it upstream. Now we are using libhighway 1.0.7, and libjxl 0.9.2.

**Comment by Alex313031** [comment]
@o-l-a-v  @Traneptora Can you try the M121 version and report back

**Comment by o-l-a-v** [comment]
@Alex313031 

They still don't look the same.

![Screenshot 2024-02-20 160838](https://github.com/Alex313031/thorium-libjxl/assets/6450056/3cae3e04-1b29-48bf-b1a7-5024500015c4)

**Comment by o-l-a-v** [comment]
> 0.9.2 is the latest publicly released version. If you still cannot get the expected results, there may be other factors affecting it.
> 
> @o-l-a-v

Sure, but that's out of my knowledge.

Thorium devs say "We fixed it, as they fixed it upstream." without even trying the test image in this issue original post apperently.
I just report that: No, the problem still persists.

**Comment by o-l-a-v** [comment]
No worries @Alex313031, I also understand that this could be out of your/Thorium's control. :)
